### PR TITLE
ENHANCE: Allow for subsites on preview link

### PR DESCRIPTION
**Pull request by tamelion**
Make preview link work for subsite, if currently administering one.

### CODE REVIEW

**Comment by alex-dna** [comment]
@icecaster Thanks for merging so quickly. Will you create a new version tag for it (I believe 1.0.2) ?Cheers

**Comment by icecaster** [comment]
@alex-dna I am not actually running any version myself at the moment, so unable to test unfortunately.
Which SS version are you working with?

**Comment by alex-dna** [comment]
@icecaster Currently we are running SS 3.6. And referenced your package as 1.0.x@stable. Happy to use dev-master, but with SS4 coming out soon, we may run into a bit of an issue.

**Comment by alex-dna** [comment]
@icecaster Seems like packagist did not update automatically. Would you be able to push the new commit to it?

**Comment by icecaster** [comment]
@alex-dna  - have updated and set up the hook for future changes to pull in automatically. Thanks for the heads up!

**Comment by alex-dna** [comment]
Great. Thanks @icecaster

**Pull request merged**
